### ISSUE TITLE
v4.0.3 unusable

### ISSUE THREAD

**Issue by tbourgain** [tanujnotes/Olauncher#343]
Hi,

I installed v4.0.3 this morning but it does not work. the application crashes at startup.
I had to uninstall and reinstall previous version (v4.0.0) which works great.
i run Android 13 on a google pixel 6a.

**Comment by tanujnotes** [comment]
I couldn't replicate this on an Android 13 device. There was a different issue which is now fixed in the latest release.
https://github.com/tanujnotes/Olauncher/releases/tag/v4.0.4

If anyone else faces the crash on startup, please let me know.

**Comment by tbourgain** [comment]
Same issue with v4.0.4 ...

**Comment by tanujnotes** [comment]
I haven't heard any complaints about v4.0.4 so this might be a one-off issue. Please try clearing data or reinstalling the app.

**Comment by erisible** [comment]
HI,

I have the exact same issue on both v4.0.3 and v4.0.4.
I've cleared data and reinstalled the app, it still crashes on startup. v4.0.0 works great, though.
I run Android 11 on a Nokia 8.1.

**Comment by tanujnotes** [comment]
Working on this. Meanwhile please install and older stable version.

**Comment by tanujnotes** [comment]
https://github.com/tanujnotes/Olauncher/releases/tag/v4.0.5

**Comment by erisible** [comment]
v4.0.5 works for me. Thank you.

**Comment by tbourgain** [comment]
This one works ok but i have to uninstall previous version, upgrade from v4.0.0 was not working.
