### ISSUE TITLE
Daily wallaper

### ISSUE THREAD

**Issue by swelbo** [tanujnotes/Olauncher#538]
Daily wallpaper is changing despite being set to off in options

**Comment by tanujnotes** [comment]
Could you please post a screenshot of the homescreen with the wallpaper?

Reinstalling should fix the issue for now.

**Comment by swelbo** [comment]
![Screenshot_20241112-120757.png](https://github.com/user-attachments/assets/8563c084-2bbd-4511-bee2-0b82c7a70b26)

**Comment by swelbo** [comment]
![Screenshot_20241112-120855.png](https://github.com/user-attachments/assets/fb2e4053-903f-4361-9a48-1bcfc5f7951f)

**Comment by jurraca** [comment]
reinstalling does not fix this issue for me. Where can I delete the app's wallpapers? Even when I reinstall from scratch, it loads the same wallpaper (that should be off). I want to go back to my default black screen.

**Comment by tanujnotes** [comment]
Not sure what's causing this. Please try reinstalling the launcher.
